name: THINGS-MEG
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.3.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - blosc=1.21.0
  - bottleneck=1.3.4
  - brotli=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - c-blosc2=2.0.4
  - ca-certificates=2022.4.26
  - cached-property=1.5.2
  - cffi=1.15.0
  - cfitsio=4.1.0
  - charls=2.3.4
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - colorspacious=1.1.2
  - cryptography=36.0.0
  - curl=7.82.0
  - cycler=0.11.0
  - cytoolz=0.11.0
  - darkdetect=0.5.1
  - dask-core=2022.2.1
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.12
  - dipy=1.5.0
  - double-conversion=3.2.0
  - eigen=3.3.7
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.4
  - ffmpeg=4.3.2
  - fontconfig=2.13.1
  - freetype=2.11.0
  - fsspec=2022.2.0
  - future=0.18.2
  - gettext=0.21.0
  - giflib=5.2.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.68.4
  - glib-tools=2.68.4
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - h5io=0.1.7
  - h5py=3.6.0
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=68.1
  - imagecodecs=2022.2.22
  - imageio=2.9.0
  - imageio-ffmpeg=0.4.7
  - ipycanvas=0.11.0
  - ipyevents=2.0.1
  - ipykernel=6.9.1
  - ipython=8.2.0
  - ipython_genutils=0.2.0
  - ipyvtklink=0.2.2
  - ipywidgets=7.6.5
  - jbig=2.1
  - jedi=0.18.1
  - joblib=1.1.0
  - jpeg=9e
  - jsoncpp=1.9.5
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.2.2
  - jupyter_console=6.4.3
  - jupyter_core=4.9.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - jxrlib=1.1
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=3.0
  - libaec=1.0.6
  - libavif=0.10.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.82.0
  - libdeflate=1.10
  - libedit=3.1.20210910
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgfortran5=11.2.0
  - libglib=2.68.4
  - libiconv=1.16
  - libidn2=2.3.2
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libnetcdf=4.8.1
  - libnghttp2=1.46.0
  - libogg=1.3.5
  - libopenblas=0.3.20
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.5
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libtasn1=4.16.0
  - libtheora=1.1.1
  - libtiff=4.3.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxml2=2.9.12
  - libxslt=1.1.33
  - libzip=1.8.0
  - libzlib=1.2.11
  - libzopfli=1.0.3
  - llvmlite=0.38.0
  - locket=0.2.1
  - loguru=0.5.3
  - lxml=4.8.0
  - lz4-c=1.9.3
  - lzo=2.10
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - mffpy=0.7.1
  - mistune=0.8.4
  - mne-base=1.0.0
  - mne-qt-browser=0.3.0
  - mock=4.0.3
  - munkres=1.1.4
  - mysql-common=8.0.28
  - mysql-libs=8.0.28
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.7.3
  - networkx=2.7.1
  - nibabel=3.2.2
  - nilearn=0.9.1
  - notebook=6.4.8
  - nspr=4.33
  - nss=3.74
  - numba=0.55.1
  - numexpr=2.7.3
  - numpy-base=1.21.5
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1o
  - orjson=3.6.8
  - packaging=21.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - patsy=0.5.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.4
  - pooch=1.6.0
  - proj=8.2.1
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pugixml=1.11.4
  - pure_eval=0.2.2
  - pycparser=2.21
  - pydicom=2.3.0
  - pygments=2.11.2
  - pymatreader=0.0.30
  - pyopenssl=22.0.0
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtgraph=0.12.4
  - pyqtwebengine=5.12.1
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytables=3.7.0
  - python=3.10.4
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - python-picard=0.7
  - python_abi=3.10
  - pyvista=0.34.0
  - pyvistaqt=0.9.0
  - pywavelets=1.3.0
  - pyzmq=22.3.0
  - qdarkstyle=3.0.2
  - qt=5.12.9
  - qtconsole=5.3.0
  - qtpy=2.0.1
  - readline=8.1.2
  - scikit-image=0.19.2
  - scikit-learn=1.0.1
  - scooby=0.5.12
  - send2trash=1.8.0
  - six=1.16.0
  - snappy=1.1.9
  - soupsieve=2.3.1
  - sqlite=3.38.2
  - stack_data=0.2.0
  - statsmodels=0.13.2
  - tbb=2021.5.0
  - tbb-devel=2021.5.0
  - terminado=0.13.1
  - testpath=0.5.0
  - threadpoolctl=2.2.0
  - tifffile=2021.7.2
  - tk=8.6.11
  - toolz=0.11.2
  - tornado=6.1
  - traitlets=5.1.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2022a
  - utfcpp=3.2.1
  - vtk=9.1.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - wrapt=1.13.3
  - x264=1!161.3030
  - xlrd=2.0.1
  - xmltodict=0.12.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.2
  - xorg-libx11=1.7.2
  - xorg-libxt=1.2.1
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=0.5.5
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - appdirs==1.4.4
    - attrs==22.1.0
    - certifi==2021.10.8
    - charset-normalizer==2.1.1
    - contourpy==1.0.5
    - et-xmlfile==1.1.0
    - fonttools==4.37.4
    - hv-proc==0.1.0
    - idna==3.4
    - importlib-resources==5.7.1
    - iniconfig==1.1.1
    - install==1.3.5
    - jinja2==3.1.2
    - kiwisolver==1.4.4
    - markupsafe==2.1.1
    - matplotlib==3.6.0
    - mne==1.2.1
    - mne-bids==0.10
    - numpy==1.23.4
    - openpyxl==3.0.9
    - pandas==1.5.1
    - pillow==9.2.0
    - pluggy==1.0.0
    - py==1.11.0
    - pyctf-lite==1.0
    - pyparsing==3.0.9
    - pytest==7.1.3
    - pytz==2022.5
    - pyyaml==6.0
    - requests==2.28.1
    - scipy==1.9.3
    - seaborn==0.12.1
    - setuptools==62.3.1
    - tomli==2.0.1
    - tqdm==4.64.1
    - urllib3==1.26.12
